# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-03 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mamtaApp', '0002_moneytocollect_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
