# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0003_admin_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycollection',
            name='chequeImage',
            field=models.ImageField(blank=True, null=True, upload_to='Cheques'),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='latitude',
            field=models.CharField(default='0.0', max_length=200),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='longitude',
            field=models.CharField(default='0.0', max_length=200),
        ),
        migrations.AddField(
            model_name='moneycollection',
            name='paymentMode',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
