# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0004_auto_20190710_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='canTakePayment',
            field=models.BooleanField(default=False),
        ),
    ]
