# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0010_auto_20191012_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycollection',
            name='isAddedInSales',
            field=models.BooleanField(default=False),
        ),
    ]
