# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0011_moneycollection_isaddedinsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycollection',
            name='companyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.Company'),
        ),
    ]
