# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0014_suppliercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercollection',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
