# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0016_loginandlogoutstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercollection',
            name='approvedBy',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
