# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceserial',
            old_name='serials',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='invoiceserial',
            name='invoiceSeriesID',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='invoiceSerialID',
        ),
        migrations.AddField(
            model_name='invoiceseries',
            name='startsWith',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='InvoiceSeriesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.InvoiceSeries'),
        ),
    ]
