# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190910_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='actualBillNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceserial',
            name='number',
            field=models.CharField(default='00001', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceseries',
            name='startsWith',
            field=models.CharField(default='00001', max_length=100),
        ),
    ]
