# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190910_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceserial',
            name='numberMain',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='numberMain',
            field=models.IntegerField(default=1),
        ),
    ]
