# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0010_auto_20191012_1254'),
        ('invoice', '0004_auto_20190910_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceseries',
            name='companyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.Company'),
        ),
    ]
