# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-12 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20191101_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceseries',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
