# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0012_moneycollection_companyid'),
        ('invoice', '0008_invoiceseries_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualBillNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('numberMain', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0.0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.StaffUser')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualBillNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('numberMain', models.IntegerField(default=1)),
                ('amount', models.FloatField(default=0.0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.StaffUser')),
            ],
        ),
    ]
