# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20200217_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='challanNumber',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
