# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_correctcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='mixCardAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
