# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-28 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0018_supplierinvoicecollection'),
        ('invoice', '0017_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningAndClosingBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingAmount', models.FloatField(default=0.0)),
                ('closingAmount', models.FloatField(default=0.0)),
                ('isBalanceCreditedOnNextDay', models.BooleanField(default=False)),
                ('balanceDate', models.DateField(blank=True, null=True)),
                ('balanceCreditDate', models.DateField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.Company')),
            ],
        ),
    ]
