# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mamtaApp', '0018_supplierinvoicecollection'),
        ('invoice', '0018_openingandclosingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingandclosingbalance',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mamtaApp.StaffUser'),
        ),
    ]
