# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-29 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', stdimage.models.StdImageField(blank=True, null=True, upload_to='Employee')),
                ('inTime', models.TimeField(null=True)),
                ('outTime', models.TimeField(null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateField(null=True)),
                ('loginTime', models.TimeField(null=True)),
                ('loginRemark', models.CharField(blank=True, max_length=500, null=True)),
                ('loginPhoto', stdimage.models.StdImageField(blank=True, null=True, upload_to='EmployeeAttendanceLogin')),
                ('logoutTime', models.TimeField(null=True)),
                ('logoutRemark', models.CharField(blank=True, max_length=500, null=True)),
                ('logoutPhoto', stdimage.models.StdImageField(blank=True, null=True, upload_to='EmployeeAttendanceLogout')),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LoginSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemName', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
