# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employeeattendance_loginsystemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='logoutSystemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logout', to='attendance.LoginSystem'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='loginSystemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='attendance.LoginSystem'),
        ),
    ]
