# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-04 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20191204_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='loginSystemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='logoutSystemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logout', to=settings.AUTH_USER_MODEL),
        ),
    ]
